[tools]
bun = "1"

[tasks.fmt]
description = "Format repo"
depends = ["fmt:*"]

[tasks."fmt:mise"]
description = "Format mise config"
run = "mise fmt"

[tasks."fmt:oxfmt"]
description = "Format files via oxfmt"
run = "bun x oxfmt --write ."

[tasks.lint]
description = "Lint repo"
depends = ["lint:*"]

[tasks."lint:oxlint"]
description = "Lint TypeScript files"
run = "bun x oxlint src .opencode"

[tasks."lint:oxfmt"]
description = "Check if files are formatted correctly"
run = "bun x oxfmt --check ."

[tasks.test]
description = "Run tests"
run = "bun test"
