[tools]
node = "22"
yarn = "4"

[tasks.fmt]
description = "Format repo"
depends = ["fmt:*"]

[tasks."fmt:mise"]
description = "Format mise config"
run = "mise fmt"

[tasks."fmt:oxfmt"]
description = "Format files via oxfmt"
run = "yarn oxfmt --write ."

[tasks.lint]
description = "Lint repo"
depends = ["lint:*"]

[tasks."lint:oxlint"]
description = "Lint JavaScript files"
run = "yarn oxlint --deny pedantic src"

[tasks."lint:oxfmt"]
description = "Check if files are formatted correctly"
run = "yarn oxfmt --check ."
