#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const crypto = require("node:crypto");
const { execFileSync } = require("node:child_process");

function sleepMs(ms) {
  const seconds = Math.ceil(ms / 1000);
  execFileSync("sleep", [String(seconds)], { stdio: "ignore" });
}
const { parseThreads } = require("./parse-threads.js");
const { classifyFindings } = require("./diff-classifier.js");
const { graphql, getPrInfo } = require("./graphql.js");

const AI_TRAILER = "\n\n---\n🤖 Review generated by AI";

function findingId(path, startLine, line) {
  const key = `${path}:${startLine || 0}:${line}`;
  return crypto.createHash("sha256").update(key).digest("hex").slice(0, 12);
}

function embedFindingId(body, id) {
  return `${body}\n<!-- finding:${id} -->`;
}

function extractFindingId(body) {
  const match = body.match(/<!-- finding:([a-f0-9]+) -->/);
  return match ? match[1] : null;
}

function buildReviewBody(tier3Findings, owner, name, headOid) {
  let body = "";
  for (const f of tier3Findings) {
    const permalink = `https://github.com/${owner}/${name}/blob/${headOid}/${f.path}#L${f.line}`;
    body += `<details>\n<summary><a href="${permalink}"><code>${f.path}:${f.line}</code></a></summary>\n\n${f.body}\n</details>\n\n`;
  }
  body += AI_TRAILER;
  return body;
}

function findPendingReview(prNodeId) {
  const data = graphql(
    `
      query ($prId: ID!) {
        node(id: $prId) {
          ... on PullRequest {
            viewerLatestReview: reviews(last: 1, states: PENDING, author: "@me") {
              nodes {
                id
                body
                comments(first: 100) {
                  totalCount
                  nodes {
                    id
                    body
                    path
                    startLine
                    line
                  }
                }
              }
            }
          }
        }
      }
    `,
    { prId: prNodeId },
  );
  const reviews = data.node.viewerLatestReview.nodes;
  if (reviews.length > 0 && reviews[0].comments.totalCount > 100) {
    const totalCount = reviews[0].comments.totalCount;
    console.warn(
      `WARN: Pending review has ${totalCount} comments, only first 100 checked for deduplication. Duplicates may occur.`,
    );
  }
  return reviews.length > 0 ? reviews[0] : null;
}

function createPendingReview(prNodeId, commitOid, body) {
  const data = graphql(
    `
      mutation ($input: AddPullRequestReviewInput!) {
        addPullRequestReview(input: $input) {
          pullRequestReview {
            id
          }
        }
      }
    `,
    {
      input: {
        pullRequestId: prNodeId,
        commitOID: commitOid,
        body,
      },
    },
  );
  return data.addPullRequestReview.pullRequestReview.id;
}

function updateReviewBody(reviewId, body) {
  graphql(
    `
      mutation ($input: UpdatePullRequestReviewInput!) {
        updatePullRequestReview(input: $input) {
          pullRequestReview {
            id
          }
        }
      }
    `,
    { input: { pullRequestReviewId: reviewId, body } },
  );
}

function addLineThread(reviewId, path, line, startLine, body) {
  const input = {
    pullRequestReviewId: reviewId,
    path,
    line,
    side: "RIGHT",
    body,
  };
  if (startLine) {
    input.startLine = startLine;
    input.startSide = "RIGHT";
  }
  graphql(
    `
      mutation ($input: AddPullRequestReviewThreadInput!) {
        addPullRequestReviewThread(input: $input) {
          thread {
            id
          }
        }
      }
    `,
    { input },
  );
}

function addFileThread(reviewId, path, body) {
  graphql(
    `
      mutation ($input: AddPullRequestReviewThreadInput!) {
        addPullRequestReviewThread(input: $input) {
          thread {
            id
          }
        }
      }
    `,
    {
      input: {
        pullRequestReviewId: reviewId,
        path,
        body,
        subjectType: "FILE",
      },
    },
  );
}

function updateExistingThreads(existingReview, findings) {
  const existingComments = existingReview.comments?.nodes || [];
  const existingById = new Map();
  for (const c of existingComments) {
    const id = extractFindingId(c.body);
    if (id) existingById.set(id, c);
  }

  const toUpdate = [];
  for (const f of findings) {
    const id = findingId(f.path, f.startLine, f.line);
    const existing = existingById.get(id);
    if (existing) {
      toUpdate.push({ finding: f, commentId: existing.id, id });
    }
  }

  for (const { finding, commentId, id } of toUpdate) {
    const body = embedFindingId(finding.body, id);
    graphql(
      `
        mutation ($input: UpdatePullRequestReviewCommentInput!) {
          updatePullRequestReviewComment(input: $input) {
            pullRequestReviewComment {
              id
            }
          }
        }
      `,
      { input: { pullRequestReviewCommentId: commentId, body } },
    );
  }

  console.log(`Updated ${toUpdate.length} existing threads.`);
  const updatedFindings = new Set(toUpdate.map(({ finding }) => finding));
  return updatedFindings;
}

function main({ readFileFn = fs.readFileSync, argv = process.argv.slice(2) } = {}) {
  const [threadsPath, prNumberStr] = argv;
  if (!threadsPath || !prNumberStr) {
    console.error("Usage: post-review.js <threads.md> <PR_NUMBER>");
    process.exit(1);
  }
  const prNumber = Number(prNumberStr);
  if (!Number.isInteger(prNumber) || prNumber <= 0) {
    console.error("Error: PR number must be a positive integer.");
    process.exit(1);
  }

  // Read threads
  const threadsContent = readFileFn(threadsPath, "utf8");
  const findings = parseThreads(threadsContent);

  if (findings.length === 0) {
    console.log("No findings to post. Exiting.");
    process.exit(0);
  }

  // Get PR info
  const { owner, name, prNodeId, headOid, state: prState } = getPrInfo(prNumber);

  if (prState !== "OPEN") {
    console.error(`PR is ${prState}. Aborting.`);
    process.exit(1);
  }

  // Check SHA freshness
  const expectedSha = process.env.PR_HEAD_SHA;
  if (expectedSha && expectedSha !== headOid) {
    console.error(
      `ABORT: PR head moved (expected ${expectedSha}, got ${headOid}). New commits landed during review.`,
    );
    process.exit(1);
  }

  // Read diff for classification
  const diff = execFileSync("gh", ["pr", "diff", String(prNumber)], { encoding: "utf8" });

  // Classify findings
  const classified = classifyFindings(findings, diff);
  const tier1 = classified.filter((f) => f.tier === 1);
  const tier2 = classified.filter((f) => f.tier === 2);
  const tier3 = classified.filter((f) => f.tier === 3);

  // Log demotions
  for (const f of tier2) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to file-level (line not in any hunk)`);
  }
  for (const f of tier3) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to review body (file not in diff)`);
  }

  // Check for existing pending review
  const existingReview = findPendingReview(prNodeId);
  let reviewId;

  let updatedFindings = new Set();

  if (existingReview) {
    reviewId = existingReview.id;
    console.log(`Found existing pending review: ${reviewId}`);
    updateReviewBody(reviewId, buildReviewBody(tier3, owner, name, headOid));
    updatedFindings = updateExistingThreads(existingReview, [...tier1, ...tier2]);
  } else {
    const reviewBody = buildReviewBody(tier3, owner, name, headOid);
    reviewId = createPendingReview(prNodeId, headOid, reviewBody);
    console.log(`Created pending review: ${reviewId}`);
  }

  // Add threads sequentially
  let failures = 0;
  const inlineFindings = [...tier1, ...tier2];
  for (const f of inlineFindings) {
    if (updatedFindings.has(f)) continue;
    const id = findingId(f.path, f.startLine, f.line);
    const body = embedFindingId(f.body, id);

    try {
      if (f.tier === 1) {
        addLineThread(reviewId, f.path, f.line, f.startLine, body);
      } else {
        addFileThread(reviewId, f.path, body);
      }
    } catch (err) {
      if (err.message.includes("rate limit") || err.message.includes("429")) {
        let posted = false;
        for (let attempt = 0; attempt < 2; attempt++) {
          console.warn(
            `Rate limited on ${f.path}:${f.line}. Waiting 60s (retry ${attempt + 1}/2)...`,
          );
          sleepMs(60_000);
          try {
            if (f.tier === 1) {
              addLineThread(reviewId, f.path, f.line, f.startLine, body);
            } else {
              addFileThread(reviewId, f.path, body);
            }
            posted = true;
            break;
          } catch (retryErr) {
            if (!(retryErr.message.includes("rate limit") || retryErr.message.includes("429"))) {
              throw retryErr;
            }
          }
        }
        if (!posted) {
          console.error(`FAIL: ${f.path}:${f.line} — rate limited after retries`);
          failures++;
        }
      } else {
        console.error(`FAIL: ${f.path}:${f.line} — ${err.message}`);
        failures++;
      }
    }
  }

  const skipped = inlineFindings.filter((f) => updatedFindings.has(f)).length;
  const attempted = inlineFindings.length - skipped;
  console.log(
    `Posted ${attempted - failures}/${attempted} inline threads (${skipped} already up-to-date). ` +
      `${tier3.length} findings in review body.`,
  );

  if (failures > 0) {
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { main };
