import { describe, it } from "bun:test";
import assert from "node:assert/strict";
import { parseThreads } from "./parse-threads.ts";
import { classifyFindings } from "./diff-classifier.ts";
import { buildReviewBody } from "./review-helpers.ts";

describe("buildReviewBody", () => {
  it("includes summary when provided and no tier3 findings", () => {
    const body = buildReviewBody([], "owner", "repo", "a".repeat(40), "Overall looks good.");
    assert.ok(body.includes("Overall looks good."));
    assert.ok(body.includes("🤖 Review generated by AI"));
  });

  it("includes both summary and tier3 findings", () => {
    const tier3 = [{ path: "pkg/other.go", line: 5, body: "Unused import.", tier: 3 as const }];
    const body = buildReviewBody(tier3, "owner", "repo", "a".repeat(40), "Has issues.");
    assert.ok(body.includes("Has issues."));
    assert.ok(body.includes("pkg/other.go"));
    assert.ok(body.includes("Unused import."));
  });

  it("works without summary (backward compatible)", () => {
    const tier3 = [{ path: "pkg/other.go", line: 5, body: "Unused import.", tier: 3 as const }];
    const body = buildReviewBody(tier3, "owner", "repo", "a".repeat(40));
    assert.ok(!body.includes("undefined"));
    assert.ok(body.includes("pkg/other.go"));
    assert.ok(body.includes("🤖 Review generated by AI"));
  });

  it("only shows trailer when no summary and no tier3 findings", () => {
    const body = buildReviewBody([], "owner", "repo", "a".repeat(40));
    assert.equal(body, "\n\n---\n🤖 Review generated by AI");
  });
});

describe("postReview reply routing", () => {
  it("classifies findings with replyTo separately from new findings", () => {
    const threadsContent = [
      "---",
      "path: src/foo.ts",
      "line: 10",
      "replyTo: PRT_kwDOABC123",
      "---",
      "Reply body here.",
      "---",
      "path: src/bar.ts",
      "line: 20",
      "---",
      "New finding body.",
    ].join("\n");

    const { findings } = parseThreads(threadsContent);
    const replyFindings = findings.filter((f) => f.replyTo !== undefined);
    const newFindings = findings.filter((f) => f.replyTo === undefined);

    assert.equal(replyFindings.length, 1);
    assert.equal(replyFindings[0].replyTo, "PRT_kwDOABC123");
    assert.equal(newFindings.length, 1);
    assert.equal(newFindings[0].path, "src/bar.ts");
  });
});

describe("integration: parse → classify", () => {
  const threadsContent = [
    "---",
    "path: src/main.go",
    "startLine: 10",
    "line: 15",
    "---",
    "Error not propagated.",
    "---",
    "path: src/main.go",
    "line: 200",
    "---",
    "Missing docs.",
    "---",
    "path: pkg/other.go",
    "line: 5",
    "---",
    "Unused import.",
  ].join("\n");

  const diff = [
    "diff --git a/src/main.go b/src/main.go",
    "index abc..def 100644",
    "--- a/src/main.go",
    "+++ b/src/main.go",
    "@@ -8,6 +8,10 @@ func main() {",
    "     existing()",
    "+    newCode()",
    "+    moreNew()",
    "+    evenMore()",
    "+    andMore()",
    "     rest()",
  ].join("\n");

  it("classifies findings correctly across all 3 tiers", () => {
    const { findings } = parseThreads(threadsContent);
    assert.equal(findings.length, 3);

    const classified = classifyFindings(findings, diff);
    // line 10-15 is within hunk (newStart=8, newLines=10) → tier 1
    assert.equal(classified[0].tier, 1);
    // line 200 in src/main.go but not in hunk → tier 2
    assert.equal(classified[1].tier, 2);
    // pkg/other.go not in diff → tier 3
    assert.equal(classified[2].tier, 3);
  });
});
