#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const crypto = require("node:crypto");
const { execFileSync } = require("node:child_process");
const { parseThreads } = require("./parse-threads.js");
const { classifyFindings } = require("./diff-classifier.js");
const { getPrInfo } = require("./graphql.js");
const {
  findPendingReview,
  createPendingReview,
  updateReviewBody,
  addLineThread,
  addFileThread,
} = require("./review-api.js");

const AI_TRAILER = "\n\n---\n🤖 Review generated by AI";
const FINDING_ID_RE = /<!-- finding:([a-f0-9]+) -->/u;

function sleepMs(ms) {
  const seconds = Math.ceil(ms / 1000);
  execFileSync("sleep", [String(seconds)], { stdio: "ignore" });
}

function isRateLimitError(err) {
  return err.message.includes("rate limit") || err.message.includes("429");
}

function findingId(path, startLine, line) {
  const key = `${path}:${startLine || 0}:${line}`;
  return crypto.createHash("sha256").update(key).digest("hex").slice(0, 12);
}

function embedFindingId(body, id) {
  return `${body}\n<!-- finding:${id} -->`;
}

function extractFindingId(body) {
  const match = body.match(FINDING_ID_RE);
  return match ? match[1] : null;
}

function buildReviewBody(tier3Findings, owner, name, headOid) {
  let body = "";
  for (const f of tier3Findings) {
    const permalink = `https://github.com/${owner}/${name}/blob/${headOid}/${f.path}#L${f.line}`;
    body += `<details>\n<summary><a href="${permalink}"><code>${f.path}:${f.line}</code></a></summary>\n\n${f.body}\n</details>\n\n`;
  }
  body += AI_TRAILER;
  return body;
}

function updateExistingThreads(existingReview, findings) {
  const { graphql } = require("./graphql.js");
  const existingComments = existingReview.comments?.nodes || [];
  const existingById = new Map();
  for (const c of existingComments) {
    const id = extractFindingId(c.body);
    if (id) existingById.set(id, c);
  }

  const toUpdate = [];
  for (const f of findings) {
    const id = findingId(f.path, f.startLine, f.line);
    const existing = existingById.get(id);
    if (existing) {
      toUpdate.push({ finding: f, commentId: existing.id, id });
    }
  }

  for (const { finding, commentId, id } of toUpdate) {
    const body = embedFindingId(finding.body, id);
    graphql(
      `
        mutation ($input: UpdatePullRequestReviewCommentInput!) {
          updatePullRequestReviewComment(input: $input) {
            pullRequestReviewComment {
              id
            }
          }
        }
      `,
      { input: { pullRequestReviewCommentId: commentId, body } },
    );
  }

  console.log(`Updated ${toUpdate.length} existing threads.`);
  return new Set(toUpdate.map(({ finding }) => finding));
}

function postThread(reviewId, finding, body) {
  if (finding.tier === 1) {
    addLineThread(reviewId, finding.path, finding.line, finding.startLine, body);
  } else {
    addFileThread(reviewId, finding.path, body);
  }
}

function postWithRetry(reviewId, finding, body) {
  try {
    postThread(reviewId, finding, body);
    return true;
  } catch (err) {
    if (!isRateLimitError(err)) {
      console.error(`FAIL: ${finding.path}:${finding.line} — ${err.message}`);
      return false;
    }
    for (let attempt = 0; attempt < 2; attempt++) {
      console.warn(
        `Rate limited on ${finding.path}:${finding.line}. Waiting 60s (retry ${attempt + 1}/2)...`,
      );
      sleepMs(60_000);
      try {
        postThread(reviewId, finding, body);
        return true;
      } catch (retryErr) {
        if (!isRateLimitError(retryErr)) {
          throw retryErr;
        }
      }
    }
    console.error(`FAIL: ${finding.path}:${finding.line} — rate limited after retries`);
    return false;
  }
}

function postInlineThreads(reviewId, inlineFindings, updatedFindings) {
  let failures = 0;
  for (const f of inlineFindings) {
    if (updatedFindings.has(f)) continue;
    const id = findingId(f.path, f.startLine, f.line);
    const body = embedFindingId(f.body, id);
    if (!postWithRetry(reviewId, f, body)) {
      failures++;
    }
  }
  return failures;
}

function validateArgs(argv) {
  const [threadsPath, prNumberStr] = argv;
  if (!threadsPath || !prNumberStr) {
    console.error("Usage: post-review.js <threads.md> <PR_NUMBER>");
    process.exit(1);
  }
  const prNumber = Number(prNumberStr);
  if (!Number.isInteger(prNumber) || prNumber <= 0) {
    console.error("Error: PR number must be a positive integer.");
    process.exit(1);
  }
  return { threadsPath, prNumber };
}

function classifyAndLog(findings, prNumber) {
  const diff = execFileSync("gh", ["pr", "diff", String(prNumber)], { encoding: "utf8" });
  const classified = classifyFindings(findings, diff);
  const tier1 = classified.filter((f) => f.tier === 1);
  const tier2 = classified.filter((f) => f.tier === 2);
  const tier3 = classified.filter((f) => f.tier === 3);

  for (const f of tier2) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to file-level`);
  }
  for (const f of tier3) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to review body`);
  }
  return { tier1, tier2, tier3 };
}

function ensureReview(prNodeId, headOid, tier1, tier2, tier3, owner, name) {
  const existingReview = findPendingReview(prNodeId);
  if (existingReview) {
    console.log(`Found existing pending review: ${existingReview.id}`);
    updateReviewBody(existingReview.id, buildReviewBody(tier3, owner, name, headOid));
    const updated = updateExistingThreads(existingReview, [...tier1, ...tier2]);
    return { reviewId: existingReview.id, updatedFindings: updated };
  }
  const reviewId = createPendingReview(
    prNodeId,
    headOid,
    buildReviewBody(tier3, owner, name, headOid),
  );
  console.log(`Created pending review: ${reviewId}`);
  return { reviewId, updatedFindings: new Set() };
}

function main({ readFileFn = fs.readFileSync, argv = process.argv.slice(2) } = {}) {
  const { threadsPath, prNumber } = validateArgs(argv);
  const findings = parseThreads(readFileFn(threadsPath, "utf8"));

  if (findings.length === 0) {
    console.log("No findings to post. Exiting.");
    process.exit(0);
  }

  const { owner, name, prNodeId, headOid, state: prState } = getPrInfo(prNumber);
  if (prState !== "OPEN") {
    console.error(`PR is ${prState}. Aborting.`);
    process.exit(1);
  }

  const expectedSha = process.env.PR_HEAD_SHA;
  if (expectedSha && expectedSha !== headOid) {
    console.error(`ABORT: PR head moved (expected ${expectedSha}, got ${headOid}).`);
    process.exit(1);
  }

  const { tier1, tier2, tier3 } = classifyAndLog(findings, prNumber);
  const { reviewId, updatedFindings } = ensureReview(
    prNodeId,
    headOid,
    tier1,
    tier2,
    tier3,
    owner,
    name,
  );

  const inlineFindings = [...tier1, ...tier2];
  const failures = postInlineThreads(reviewId, inlineFindings, updatedFindings);
  const skipped = inlineFindings.filter((f) => updatedFindings.has(f)).length;
  const attempted = inlineFindings.length - skipped;
  console.log(
    `Posted ${attempted - failures}/${attempted} inline threads (${skipped} up-to-date). ` +
      `${tier3.length} findings in review body.`,
  );

  if (failures > 0) {
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { main };
