import { readFile, realpath } from "node:fs/promises";
import { resolve } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { parseThreads } from "./parse-threads.ts";
import { classifyFindings } from "./diff-classifier.ts";
import type { Finding, ClassifiedFinding } from "./diff-classifier.ts";
import { type PrInfo, getPrInfo } from "./graphql.ts";
import {
  type PendingReview,
  findPendingReview,
  createPendingReview,
  updateReviewBody,
  addLineThread,
  addFileThread,
  updateReviewComment,
} from "./review-api.ts";
import {
  escapeHtml,
  isValidPath,
  sleepMs,
  isRateLimitError,
  findingId,
  embedFindingId,
  extractFindingId,
} from "./review-helpers.ts";

// oxlint-disable-next-line typescript/strict-void-return -- Why: promisify() overload resolution picks void-returning signature incorrectly
const execFileAsync = promisify(execFile);

export interface PostReviewOptions {
  threadsPath: string;
  prNumber: number;
  dryRun?: boolean;
  skipIds?: string[];
  expectedSha?: string;
  cwd?: string;
  diffText?: string;
}

export interface PostReviewResult {
  summary: string;
  failed: string[];
}

const AI_TRAILER = "\n\n---\n🤖 Review generated by AI";

function buildReviewBody(
  tier3Findings: ClassifiedFinding[],
  owner: string,
  name: string,
  headOid: string,
): string {
  let body = "";
  for (const f of tier3Findings) {
    if (!isValidPath(f.path)) {
      console.warn(`WARN: Skipping finding with suspicious path: ${f.path}`);
      continue;
    }
    const permalink = `https://github.com/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/blob/${headOid}/${encodeURI(f.path)}#L${f.line}`;
    // Neutralize all HTML tags — GitHub re-renders markdown inside <details>.
    const safeBody = f.body.replaceAll(/</gu, "&lt;");
    body += `<details>\n<summary><a href="${permalink}"><code>${escapeHtml(f.path)}:${f.line}</code></a></summary>\n\n${safeBody}\n</details>\n\n`;
  }
  body += AI_TRAILER;
  return body;
}

async function updateExistingThreads(
  existingReview: PendingReview,
  findings: ClassifiedFinding[],
): Promise<Set<string>> {
  const existingComments = existingReview.comments.nodes;
  const existingById = new Map<string, { id: string; body: string }>();
  for (const c of existingComments) {
    const id = extractFindingId(c.body);
    if (id !== null) existingById.set(id, c);
  }

  const toUpdate: Array<{ finding: ClassifiedFinding; commentId: string; id: string }> = [];
  for (const f of findings) {
    const id = findingId(f.path, f.startLine, f.line, f.body);
    const existing = existingById.get(id);
    if (existing) {
      toUpdate.push({ finding: f, commentId: existing.id, id });
    }
  }

  for (const { finding, commentId, id } of toUpdate) {
    const body = embedFindingId(finding.body, id);
    await updateReviewComment(commentId, body);
  }

  console.log(`Updated ${toUpdate.length} existing threads.`);
  return new Set(toUpdate.map(({ id }) => id));
}

async function postThread(
  reviewId: string,
  finding: ClassifiedFinding,
  body: string,
): Promise<void> {
  if (finding.tier === 1) {
    await addLineThread(reviewId, finding.path, finding.line, finding.startLine, body);
  } else {
    await addFileThread(reviewId, finding.path, body);
  }
}

async function postWithRetry(
  reviewId: string,
  finding: ClassifiedFinding,
  body: string,
): Promise<boolean> {
  try {
    await postThread(reviewId, finding, body);
    return true;
  } catch (err: unknown) {
    if (!isRateLimitError(err)) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`FAIL: ${finding.path}:${finding.line} — ${message}`);
      return false;
    }
    for (let attempt = 0; attempt < 2; attempt++) {
      console.warn(
        `Rate limited on ${finding.path}:${finding.line}. Waiting 60s (retry ${attempt + 1}/2)...`,
      );
      await sleepMs(60_000);
      try {
        await postThread(reviewId, finding, body);
        return true;
      } catch (retryErr: unknown) {
        if (!isRateLimitError(retryErr)) {
          throw retryErr;
        }
      }
    }
    console.error(`FAIL: ${finding.path}:${finding.line} — rate limited after retries`);
    return false;
  }
}

async function postInlineThreads(
  reviewId: string,
  inlineFindings: ClassifiedFinding[],
  updatedIds: Set<string>,
): Promise<string[]> {
  const CONCURRENCY = 5;
  const failedFindings: string[] = [];
  const pending = inlineFindings.filter(
    (f) => !updatedIds.has(findingId(f.path, f.startLine, f.line, f.body)),
  );

  for (let i = 0; i < pending.length; i += CONCURRENCY) {
    if (i > 0) await sleepMs(200);
    const batch = pending.slice(i, i + CONCURRENCY);
    const results = await Promise.all(
      batch.map(async (f) => {
        const id = findingId(f.path, f.startLine, f.line, f.body);
        const body = embedFindingId(f.body, id);
        const ok = await postWithRetry(reviewId, f, body);
        return ok ? null : id;
      }),
    );
    for (const id of results) {
      if (id !== null) failedFindings.push(id);
    }
  }
  return failedFindings;
}

function classifyAndLog(
  findings: Finding[],
  diff: string,
): { tier1: ClassifiedFinding[]; tier2: ClassifiedFinding[]; tier3: ClassifiedFinding[] } {
  const validated = findings.filter((f) => {
    if (!isValidPath(f.path)) {
      console.warn(`WARN: Skipping finding with suspicious path: ${f.path}`);
      return false;
    }
    return true;
  });
  const classified = classifyFindings(validated, diff);
  const tier1 = classified.filter((f) => f.tier === 1);
  const tier2 = classified.filter((f) => f.tier === 2);
  const tier3 = classified.filter((f) => f.tier === 3);

  for (const f of tier2) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to file-level`);
  }
  for (const f of tier3) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to review body`);
  }
  return { tier1, tier2, tier3 };
}

async function ensureReview(
  prNodeId: string,
  headOid: string,
  tier1: ClassifiedFinding[],
  tier2: ClassifiedFinding[],
  tier3: ClassifiedFinding[],
  owner: string,
  name: string,
): Promise<{ reviewId: string; updatedFindings: Set<string> }> {
  const existingReview = await findPendingReview(prNodeId);
  if (existingReview) {
    console.log(`Found existing pending review: ${existingReview.id}`);
    await updateReviewBody(existingReview.id, buildReviewBody(tier3, owner, name, headOid));
    const updated = await updateExistingThreads(existingReview, [...tier1, ...tier2]);
    return { reviewId: existingReview.id, updatedFindings: updated };
  }
  const reviewId = await createPendingReview(
    prNodeId,
    headOid,
    buildReviewBody(tier3, owner, name, headOid),
  );
  console.log(`Created pending review: ${reviewId}`);
  return { reviewId, updatedFindings: new Set() };
}

async function loadAndValidatePr(
  threadsPath: string,
  prNumber: number,
  expectedSha: string | undefined,
  cwd: string | undefined,
): Promise<{ findings: Finding[]; prInfo: PrInfo } | null> {
  if (!isValidPath(threadsPath)) {
    throw new Error(`Invalid threadsPath: ${threadsPath}`);
  }
  const base = await realpath(resolve(cwd ?? process.cwd()));
  const resolved = await realpath(resolve(base, threadsPath));
  if (!resolved.startsWith(base + "/") && resolved !== base) {
    throw new Error(`threadsPath escapes working directory: ${threadsPath}`);
  }
  const content = await readFile(resolved, "utf8");
  const findings = parseThreads(content);
  if (findings.length === 0) return null;

  const prInfo = await getPrInfo(prNumber, { cwd });
  if (prInfo.state !== "OPEN") {
    throw new Error(`PR is ${prInfo.state}. Aborting.`);
  }

  const resolvedSha = expectedSha ?? process.env.PR_HEAD_SHA;
  if (resolvedSha !== undefined && resolvedSha !== "" && resolvedSha !== prInfo.headOid) {
    throw new Error(`ABORT: PR head moved (expected ${resolvedSha}, got ${prInfo.headOid}).`);
  }

  return { findings, prInfo };
}

async function postFindings(
  tier1: ClassifiedFinding[],
  tier2: ClassifiedFinding[],
  tier3: ClassifiedFinding[],
  prInfo: PrInfo,
  skipIds: string[],
): Promise<PostReviewResult> {
  const { owner, name, prNodeId, headOid } = prInfo;
  const { reviewId, updatedFindings } = await ensureReview(
    prNodeId,
    headOid,
    tier1,
    tier2,
    tier3,
    owner,
    name,
  );

  const skipSet = new Set(skipIds);
  const inlineFindings = [...tier1, ...tier2].filter((f) => {
    const id = findingId(f.path, f.startLine, f.line, f.body);
    return !skipSet.has(id);
  });

  const failedIds = await postInlineThreads(reviewId, inlineFindings, updatedFindings);
  const skipped =
    inlineFindings.length -
    inlineFindings.filter(
      (f) => !updatedFindings.has(findingId(f.path, f.startLine, f.line, f.body)),
    ).length;
  const posted = inlineFindings.length - skipped - failedIds.length;
  const summary =
    `Posted ${posted}/${inlineFindings.length} inline threads (${skipped} up-to-date, ${failedIds.length} failed). ` +
    `${tier3.length} findings in review body.`;

  console.log(summary);

  return { summary, failed: failedIds };
}

/**
 * Post a review to a GitHub PR.
 */
export async function postReview(opts: PostReviewOptions): Promise<PostReviewResult> {
  const { threadsPath, prNumber, dryRun = false, skipIds = [], expectedSha } = opts;

  const result = await loadAndValidatePr(threadsPath, prNumber, expectedSha, opts.cwd);
  if (!result) return { summary: "No findings to post.", failed: [] };

  const { findings, prInfo } = result;
  const diff =
    opts.diffText ??
    (
      await execFileAsync("gh", ["pr", "diff", String(prNumber)], {
        encoding: "utf8",
        maxBuffer: 10 * 1024 * 1024,
        signal: AbortSignal.timeout(30_000),
        cwd: opts.cwd,
      })
    ).stdout;
  const { tier1, tier2, tier3 } = classifyAndLog(findings, diff);

  if (dryRun) {
    return {
      summary: `Dry run: ${tier1.length} line-level, ${tier2.length} file-level, ${tier3.length} review-body findings.`,
      failed: [],
    };
  }

  return postFindings(tier1, tier2, tier3, prInfo, skipIds);
}
