import crypto from "node:crypto";
import { classifyFindings, type Finding, type ClassifiedFinding } from "./diff-classifier.ts";

const FINDING_ID_RE = /<!-- finding:([a-f0-9]+) -->/u;
const AI_TRAILER = "\n\n---\n🤖 Review generated by AI";
const GITHUB_NAME_RE = /^[a-zA-Z0-9](?:[a-zA-Z0-9._-]*[a-zA-Z0-9])?$/u;
const SUGGESTION_OPEN_RE = /^```suggestion\b/u;

export function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function isValidPath(filePath: string): boolean {
  if (filePath.includes("\0")) return false;
  if (filePath.startsWith("/") || filePath.includes("..")) return false;
  if (filePath === "") return false;
  // Normalize away harmless . and trailing slashes before comparison
  const normalized = filePath
    .split("/")
    .filter((s) => s !== "." && s !== "")
    .join("/");
  return normalized.length > 0;
}

export interface RateLimitLike {
  status?: number;
  type?: string;
  message?: string;
}

export function isRateLimitError(err: unknown): boolean {
  if (err === null || typeof err !== "object") return false;
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- Why: narrowed to object via typeof guard; property access checked individually below
  const e = err as Record<string, unknown>;
  const status = typeof e.status === "number" ? e.status : undefined;
  const type = typeof e.type === "string" ? e.type : undefined;
  const message = typeof e.message === "string" ? e.message.toLowerCase() : "";

  if (status === 429) return true;
  if (status === 403) {
    return message.includes("rate limit") || message.includes("secondary rate limit");
  }
  if (type === "RATE_LIMITED") return true;
  return message.includes("rate limit") || message.includes("secondary rate limit");
}

export function findingId(
  path: string,
  startLine: number | undefined,
  line: number,
  body = "",
): string {
  const key = `${path}:${startLine ?? 0}:${line}:${body.slice(0, 200)}`;
  return crypto.createHash("sha256").update(key).digest("hex").slice(0, 12);
}

export function embedFindingId(body: string, id: string): string {
  return `${body}\n<!-- finding:${id} -->`;
}

export function extractFindingId(body: string): string | null {
  const match = FINDING_ID_RE.exec(body);
  return match ? match[1] : null;
}

/** @internal Not part of the public API — subject to change without notice. */
export function buildReviewBody(
  tier3Findings: ClassifiedFinding[],
  owner: string,
  name: string,
  headOid: string,
  summary?: string,
): string {
  const validOid = /^[0-9a-f]{40,64}$/u.test(headOid);
  if (!validOid) {
    console.warn(`WARN: Invalid headOid format (${headOid}). Skipping permalinks.`);
  }
  const validRepo = GITHUB_NAME_RE.test(owner) && GITHUB_NAME_RE.test(name);
  if (!validRepo) {
    console.warn(`WARN: Invalid owner/name format (${owner}/${name}). Skipping permalinks.`);
  }
  let body = "";
  if (summary !== undefined && summary !== "") {
    // Trust boundary: summary is AI-generated Markdown from the formatter agent,
    // rendered by GitHub's Markdown sanitizer (same trust level as finding bodies).
    body += summary + "\n\n";
  }
  for (const f of tier3Findings) {
    if (!isValidPath(f.path)) {
      console.warn(`WARN: Skipping finding with suspicious path: ${f.path}`);
      continue;
    }
    if (validOid && validRepo) {
      const permalink = `https://github.com/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/blob/${headOid}/${f.path.split("/").map(encodeURIComponent).join("/")}#L${f.line}`;
      body += `<details>\n<summary><a href="${permalink}"><code>${escapeHtml(f.path)}:${f.line}</code></a></summary>\n\n${f.renderedBody ?? f.body}\n</details>\n\n`;
    } else {
      body += `<details>\n<summary><code>${escapeHtml(f.path)}:${f.line}</code></summary>\n\n${f.renderedBody ?? f.body}\n</details>\n\n`;
    }
  }
  body += AI_TRAILER;
  return body;
}

export function classifyAndLog(
  findings: Finding[],
  diff: string,
): { tier1: ClassifiedFinding[]; tier2: ClassifiedFinding[]; tier3: ClassifiedFinding[] } {
  const validated = findings.filter((f) => {
    if (!isValidPath(f.path)) {
      console.warn(`WARN: Skipping finding with suspicious path: ${f.path}`);
      return false;
    }
    return true;
  });
  const classified = classifyFindings(validated, diff);
  const tier1 = classified.filter((f) => f.tier === 1);
  const tier2 = classified.filter((f) => f.tier === 2);
  const tier3 = classified.filter((f) => f.tier === 3);

  for (const f of tier2) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to file-level`);
  }
  for (const f of tier3) {
    console.warn(`WARN: ${f.path}:${f.line} demoted to review body`);
  }
  const suggestionWarnings = validateSuggestionAnchors(classified);
  for (const w of suggestionWarnings) {
    console.warn(w);
  }
  // Strip all suggestion blocks from findings where the largest block exceeds the anchor range
  const oversized = findingsExceedingAnchor(classified);
  for (const f of tier1) {
    if (oversized.has(f)) {
      f.renderedBody = stripSuggestionBlocks(f.body);
    }
  }
  return { tier1, tier2, tier3 };
}

/**
 * Count lines inside each ```suggestion block in a finding body.
 * Returns the maximum line count across all suggestion blocks, or 0 if none.
 */
function maxSuggestionLines(body: string): number {
  let max = 0;
  let inSuggestion = false;
  let count = 0;
  for (const line of body.split("\n")) {
    if (!inSuggestion && SUGGESTION_OPEN_RE.test(line.trim())) {
      inSuggestion = true;
      count = 0;
    } else if (inSuggestion && line.trim() === "```") {
      inSuggestion = false;
      max = Math.max(max, count);
    } else if (inSuggestion) {
      count++;
    }
  }
  if (inSuggestion) {
    max = Math.max(max, count);
  }
  return max;
}

/**
 * Remove all ```suggestion blocks from a finding body, preserving other content.
 */
function stripSuggestionBlocks(body: string): string {
  const lines = body.split("\n");
  const result: string[] = [];
  let inSuggestion = false;
  let pendingBlock: string[] = [];
  for (const line of lines) {
    if (!inSuggestion && SUGGESTION_OPEN_RE.test(line.trim())) {
      inSuggestion = true;
      pendingBlock = [line];
    } else if (inSuggestion && line.trim() === "```") {
      inSuggestion = false;
      pendingBlock = [];
    } else if (inSuggestion) {
      pendingBlock.push(line);
    } else {
      result.push(line);
    }
  }
  if (inSuggestion) {
    // Unclosed block — preserve all lines as-is
    result.push(...pendingBlock);
  }
  return result.join("\n");
}

/**
 * Identify tier-1 findings whose largest suggestion block exceeds the anchor range.
 * Returns a Set of findings that need their suggestion blocks stripped.
 */
function findingsExceedingAnchor(findings: ClassifiedFinding[]): Set<ClassifiedFinding> {
  const exceeded = new Set<ClassifiedFinding>();
  for (const f of findings) {
    if (f.tier !== 1) continue;
    const suggLines = maxSuggestionLines(f.body);
    if (suggLines === 0) continue;
    const anchorLines = f.startLine === undefined ? 1 : Math.max(1, f.line - f.startLine + 1);
    if (suggLines > anchorLines) {
      exceeded.add(f);
    }
  }
  return exceeded;
}

/**
 * Validate that suggestion blocks fit within their anchor ranges.
 * Returns warning messages for findings where the suggestion has more lines
 * than the anchor range (startLine..line), which often indicates the anchor
 * should be widened to cover all lines being replaced.
 *
 * Only checks tier 1 findings (line-level comments with actual anchors).
 */
export function validateSuggestionAnchors(findings: ClassifiedFinding[]): string[] {
  const warnings: string[] = [];
  const oversized = findingsExceedingAnchor(findings);
  for (const f of oversized) {
    const suggLines = maxSuggestionLines(f.body);
    const anchorLines = f.startLine === undefined ? 1 : Math.max(1, f.line - f.startLine + 1);
    const anchor =
      f.startLine === undefined ? `${f.path}:${f.line}` : `${f.path}:${f.startLine}-${f.line}`;
    warnings.push(
      `WARN: ${anchor} has ${anchorLines}-line anchor but ${suggLines}-line suggestion — anchor should be widened to cover all lines being replaced`,
    );
  }
  return warnings;
}
